services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  messaging:
    build:
      context: .
      dockerfile: ./apps/messaging/Dockerfile
      target: development
    command: pnpm run start:dev messaging
    env_file:
      - ./apps/messaging/.env
    ports:
      - '3004:3004'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  webhooks:
    build:
      context: .
      dockerfile: ./apps/webhooks/Dockerfile
      target: development
    command: pnpm run start:dev webhooks
    env_file:
      - ./apps/webhooks/.env
    ports:
      - '3006:3006'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
